config/routes.rb
Rails.application.routes.draw do

  root 'contents#index'
  get 'pages' => 'contents#pages'

  resources :sendgrid do
    match :callback, on: :collection, via: [:get, :post]
  end
  
  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/email_history.rb
class EmailHistory < ApplicationRecord
  
  enum event: {
    sent: 0,
    processed: 1,
    deferred: 2,
    delivered: 3,
    open: 4,
    click: 5,
    bounce: 6,
    dropped: 7,
    spamreport: 8,
    unsubscribe: 9,
    group_unsubscribe: 10,
    group_resubscribe: 11,
  }
  
  after_create_commit { MessageBroadcastJob.perform_later self }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
  
  end
  
  def pages
  
  end
  
end

app/controllers/sendgrid_controller.rb
class SendgridController < ApplicationController
  
  skip_before_action :verify_authenticity_token, :only => [:callback]
  before_action :authenticate, :except => [:callback]


  def index
    @email_histories = EmailHistory.order('id desc').all
  end
  
  def create
    SendgridMailer.send_test(params[:email]).deliver_now if params[:email].present?
    email_history = EmailHistory.new
    email_history.email = params[:email]
    email_history.event = 'sent'
    email_history.save
    redirect_to '/sendgrid'
  end
  
  def callback
    email_histories = []
    update_status = ["deferred", "bounce", "dropped"]
    params["_json"].each do |item|
      email_history = EmailHistory.new
      email_history.email = item['email']
      email_history.reason = item.permit!.to_h
      email_history.event = item["event"]
      email_history.save
      email_histories << email_history
    end if params["_json"]
    render plain: 'Sendgrid'
  end
  
  private

  def authenticate
    return if Rails.env == "test"
    authenticate_or_request_with_http_basic do |username, password|
      (username == "ene" && password == "pass")
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/views/contents/index.html.erb
<dt>
  <dt>Referer:</dt>
  <dd><%= request.referer %></dd>
</dt>

<ul>
  <li><%= link_to '2nd Page', '/pages' %></li>
  <li><%= link_to '2nd Page with args', '/pages?test=test' %></li>
</ul>

<ul>
  <li><%= link_to 'Github', 'https://github.com/sumiki/referer-check', {target: '_blank'} %></li>
  <li><%= link_to 'Google Doc', 'https://docs.google.com/document/d/1WxxVCAGRxl_llSjnRvw6OkfSy3ud2Er7MAGp6mxvUnA/edit', {target: '_blank'} %></li>
  <li><%= link_to 'Dropbox Paper', 'https://paper.dropbox.com/doc/referer-check--AiZjfEkJgX5feFOHAn6pA7~FAg-cmmHm5OTZOHadc9skH5zD', {target: '_blank'} %></li>
</ul>

app/views/contents/pages.html.erb
<dt>
<dt>Referer:</dt>
<dd><%= request.referer %></dd>
</dt>

<ul>
  <li><%= link_to 'Top Page', '/' %></li>
</ul>

app/views/email_histories/_email_history.html.erb
<tr>
  <td><%= email_history.created_at.strftime('%Y/%m/%d %H:%M') %></td>
  <td><%= email_history.email %></td>
  <td><%= email_history.event %></td>
  <td><%= email_history.reason %></td>
</tr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RefererCheck</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sendgrid/index.html.erb
<%= form_tag sendgrid_index_path do %>
  <%= text_field_tag :email %>
  <%= submit_tag 'Send Test Email' %>
<% end %>

<hr />

<table>
  <tr>
    <th>Time</th>
    <th>Email</th>
    <th>Event</th>
    <th>Reason</th>
  </tr>
  <tbody id="email_histories">
    <%= render @email_histories  %>
  </tbody>

</table>